# Generated by Django 4.2.1 on 2023-06-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='nivel',
        ),
    ]
