# Generated by Django 4.2.1 on 2023-06-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_remove_comunicado_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='nivel',
            field=models.CharField(choices=[('GEN', 'General'), ('PRE', 'Ciclo Preescolar'), ('BAS', 'Ciclo Básico'), ('MED', 'Ciclo Medio')], default=('GEN', 'General'), max_length=50),
        ),
    ]
